import type { ExerciseInfo } from './exerciseInfo'

// Source: "Fitness First The Mall Thapra Equipments" — personal Notion cheat sheet.
// Credit: https://www.facebook.com/watch/?v=1000456840674433
export const FITNESS_FIRST_THAPRA_SEED: ExerciseInfo[] = [
  {
    exerciseName: 'Leg Press',
    category: 'Legs', type: 'Compound', difficulty: 1, priority: 'High',
    details: {
      status: '✅ Verified',
      setupChecklist: [
        'หลัง/สะโพกแนบเบาะก่อนเริ่ม',
        'วางเท้าให้เข่าอยู่แนวเดียวกับปลายเท้า',
        'ปรับระยะที่นั่งให้เข่าไม่พับลึกเกิน',
        'เริ่มน้ำหนักเบาแล้วค่อยเพิ่ม',
      ],
      useInWorkout: 'Full Body A/B/C: ท่าหลักของขา — ใช้เป็น lower-body compound หลักก่อน isolation',
      mySetting: 'Seat: ? | Weight: ? | Reps: 10–12 | Note: ?',
      benefits: 'บริหารกล้ามเนื้อหน้าขา ก้น และหลังขา เพิ่มกำลังขาและช่วยสร้างความแข็งแรงของร่างกายส่วนล่าง',
      primaryMuscle: ['หน้าต้นขา (Quadriceps)'],
      secondaryMuscle: ['ก้น (Gluteus Maximus)', 'หลังต้นขา (Hamstrings)', 'ต้นขาด้านใน (Adductors)', 'น่อง (Calves) เล็กน้อย'],
      muscleCues: ['ดันพื้นด้วยส้นเท้า', 'คิดว่าดันแท่นด้วยต้นขา ไม่ใช่เข่า', 'ตอนบนบีบก้นเล็กน้อย'],
      feelShould: ['หน้าขา', 'ก้น'],
      feelShouldNot: ['เข่า'],
      howTo: [
        'นั่งลงไปตรงเบาะ โดยศีรษะ/หลัง/สะโพกติดกับเบาะ',
        'ปรับระยะที่นั่ง แล้ววางเท้าให้หัวเข่าอยู่ในมุมฉาก',
        'เวลาดันขึ้นให้หายใจออก ออกแรง และโฟกัสที่ต้นขาและก้น',
        'หายใจเข้า แล้วผ่อนแรงลงช้าๆ',
      ],
      romDown: 'เข่างอประมาณ 90–120°',
      romUp: 'เข่าเกือบตรง แต่ไม่ล็อก',
      commonMistakes: ['ล็อกเข่า', 'ยกก้น', 'ดันด้วยปลายเท้า'],
      adjustmentPoints: ['จุดปรับระยะขา (บีบเพื่อปรับระยะ)', 'จุดปรับน้ำหนัก'],
      breathingOut: 'ดันขึ้น',
      breathingIn: 'ผ่อนลง',
      cautions: ['ไม่ควรให้เข่าตึงเกินไป', 'ไม่ควรให้ก้นและสะโพกยกขึ้นมาด้านบน'],
    },
  },
  {
    exerciseName: 'Chest Press',
    category: 'Push', type: 'Compound', difficulty: 1, priority: 'High',
    details: {
      status: '✅ Verified',
      setupChecklist: [
        'ปรับเบาะให้มือจับอยู่ระดับอก',
        'หลัง/ก้นแนบเบาะ',
        'กดไหล่ลงและบีบสะบักเบาๆ',
        'ใช้ตัวเซฟตี้ตอนเริ่มและจบเซ็ต',
      ],
      useInWorkout: 'Full Body A/C: ท่าดันหลักของหน้าอก — ถ้าไหล่ล้า ให้ลดน้ำหนักหรือเปลี่ยนเป็น Pectoral เบาๆ',
      mySetting: 'Seat: ? | Weight: ? | Reps: 10–12 | Note: ?',
      benefits: 'บริหารกล้ามเนื้อหน้าอก เพิ่มความแข็งแรงของร่างกายส่วนบน และช่วยพัฒนาการดัน',
      primaryMuscle: ['หน้าอก (Pectoralis Major)'],
      secondaryMuscle: ['หัวไหล่ด้านหน้า (Anterior Deltoid)', 'หลังแขน (Triceps)'],
      muscleCues: ['ผลักจากหน้าอก', 'บีบอกตอนสุด', 'อย่ายักไหล่'],
      feelShould: ['หน้าอก', 'หน้าไหล่นิดหน่อย'],
      feelShouldNot: ['หัวไหล่เจ็บ'],
      howTo: [
        'นั่งให้ศีรษะ/หลัง/ก้น ติดกับเบาะ',
        'เหยียบตัวเซฟตี้เพื่อดันแฮนเดิลให้ออกมาด้านหน้า ช่วยลดการเหยียดของหัวไหล่ในจังหวะเริ่มต้น',
        'จับแฮนเดิล (บาร์แนวนอน) แล้วยืดหน้าอก/กดข้อศอก/กดไหล่ลง',
        'ปล่อยตัวเซฟตี้ แล้วดันออกไป (คุมแรง)',
        'ค่อยๆเปิดข้อศอกช้าๆ ดันขึ้น แล้วปล่อยลง โดยยืดหน้าอกและบีบสะบักไว้',
        'เมื่อจบเซ็ต ให้เหยียบตัวเซฟตี้ แล้วค่อยปล่อยมือ',
      ],
      romDown: 'หน้าอกตึง แต่หัวไหล่ไม่หลุด',
      romUp: 'แขนเกือบตรง แต่ไม่ล็อกศอก',
      commonMistakes: ['ยักไหล่', 'ก้นลอย', 'ศอกกาง 90°'],
      adjustmentPoints: ['จุดปรับระดับเบาะที่นั่ง ให้แฮนเดิลจับอยู่ในระดับของอกพอดี', 'จุดปรับน้ำหนัก'],
      breathingOut: 'ดันออก',
      breathingIn: 'ปล่อยกลับ',
      cautions: ['กดข้อศอกและกดหัวไหล่ลง เพื่อให้กล้ามเนื้อทำงานเต็มที่ และไม่ให้หัวไหล่ทำงานมากเกินไป'],
    },
  },
  {
    exerciseName: 'Lat Pulldown',
    category: 'Pull', type: 'Compound', difficulty: 2, priority: 'High',
    details: {
      status: '✅ Verified',
      setupChecklist: [
        'ล็อกหัวเข่าให้แน่นพอดี',
        'จับบาร์กว้างกว่าหัวไหล่',
        'เชิดอกและกดสะบักลงก่อนดึง',
        'เลือกน้ำหนักที่ไม่ต้องเหวี่ยงตัว',
      ],
      useInWorkout: 'Full Body A/B/C: ท่าดึงหลักสำหรับหลัง/ปีก — เล่นก่อน row isolation/accessory',
      mySetting: 'Knee pad: ? | Weight: ? | Reps: 10–12 | Note: ?',
      benefits: 'บริหารกล้ามเนื้อปีกและหลังส่วนบน ช่วยเพิ่มความกว้างของแผ่นหลัง',
      primaryMuscle: ['ปีก (Latissimus Dorsi)'],
      secondaryMuscle: ['กล้ามเนื้อระหว่างสะบัก (Rhomboids)', 'กลางหลัง (Middle/Lower Trapezius)', 'หัวไหล่ด้านหลัง (Rear Deltoids)', 'หน้าแขน (Biceps)', 'แขนท่อนล่าง (Brachialis/Brachioradialis)'],
      muscleCues: ['กดสะบักลงก่อนเริ่มดึง (Scapular Depression)', 'คิดว่า "เอาศอกใส่กระเป๋าหลัง"', 'ไม่ใช่ดึงด้วยมือ', 'หน้าอกเชิดตลอด'],
      feelShould: ['ปีก', 'กลางหลัง'],
      feelShouldNot: ['คอ', 'แขนล้าอย่างเดียว'],
      howTo: [
        'นั่งและจัดท่าให้มั่นคง แล้วล็อกหัวเข่าให้เรียบร้อย',
        'จับบาร์ให้กว้างกว่าหัวไหล่ จากนั้นล็อกลำตัวช่วงล่างให้อยู่กับที่',
        'ดึงบาร์ลงโดยเปิดข้อศอก ให้บาร์แตะบริเวณหน้าอกและต่ำกว่าคาง',
        'ค่อยๆดึงบาร์กลับขึ้น (คุมแรง ไม่ปล่อยเร็ว)',
      ],
      romDown: 'บาร์แตะช่วงอกบน',
      romUp: 'หลังยังตึงอยู่ ไม่ปล่อยจนไหล่ลอย',
      commonMistakes: ['ดึงหลังคอ', 'เหวี่ยงตัว', 'ดึงด้วยแขน'],
      adjustmentPoints: ['จุดล็อกหัวเข่า ปรับให้พอดีกับหัวเข่า', 'ลักษณะการจับ: กว้างกว่าช่วงหัวไหล่', 'จุดปรับน้ำหนัก'],
      breathingOut: 'ดึงลง',
      breathingIn: 'ดึงขึ้น',
      cautions: ['ล็อกลำตัวช่วงล่างให้อยู่กับเบาะและอยู่กับที่', 'เวลาปล่อยแขนไม่ควรกระชากบริเวณข้อศอกและหัวไหล่'],
    },
  },
  {
    exerciseName: 'Low Row',
    category: 'Pull', type: 'Compound', difficulty: 2, priority: 'High',
    details: {
      status: '✅ Verified',
      setupChecklist: [
        'ปรับเบาะให้หน้าอกแตะเบาะหน้า',
        'เท้าวางที่พักเท้าให้มั่นคง',
        'จับแฮนเดิลแล้วตั้งอก',
        'เลือกน้ำหนักที่ดึงได้โดยไม่โยกตัว',
      ],
      useInWorkout: 'Full Body A/B/C: ท่าดึงหลักสำหรับความหนาหลัง — Substitute: Seated Cable Row',
      mySetting: 'Seat: ? | Chest pad: ? | Weight: ? | Reps: 10–12 | Note: ?',
      benefits: 'เน้นความหนาของหลังและสะบัก (ต่างจาก Lat Pulldown ที่เน้นความกว้างและกล้ามเนื้อปีก)',
      primaryMuscle: ['กล้ามเนื้อระหว่างสะบัก (Rhomboids)', 'กลางหลัง (Middle Trapezius)'],
      secondaryMuscle: ['ปีก (Latissimus Dorsi)', 'หัวไหล่ด้านหลัง (Rear Deltoids)', 'หน้าแขน (Biceps)', 'แขนท่อนล่าง (Brachialis)'],
      muscleCues: ['คิดว่าหนีบดินสอไว้ระหว่างสะบัก', 'ศอกลากไปข้างหลัง', 'ไม่ใช่ดึงด้วยแขน'],
      feelShould: ['กลางหลัง', 'สะบัก'],
      feelShouldNot: ['หลังล่าง'],
      howTo: [
        'นั่งให้หน้าอกแตะกับเบาะด้านหน้าตลอด และเท้าทั้งสองวางที่พักเท้า',
        'จับแฮนเดิลทั้งสองข้าง แล้วล็อกตัว/ยืดหน้าอก',
        'ดึงเข้าโดยบีบสะบัก และให้ศอกชิดลำตัวหรือกางออกจากลำตัวเล็กน้อย (~45°) ไม่กางสูงถึงระดับไหล่',
        'ปล่อยแขนออก แล้วดึงเข้าอีกครั้ง (คุมแรงตลอดจังหวะ)',
      ],
      romDown: 'หลังยืด',
      romUp: 'ศอกเลยลำตัวนิดเดียว',
      commonMistakes: ['โยกตัว', 'หลังงอ', 'ปล่อยน้ำหนักกระแทก'],
      adjustmentPoints: ['ปรับเบาะให้ปลายนิ้วแตะแฮนเดิลพอดี', 'ปรับเบาะนั่งให้เบาะด้านหน้าอยู่ใต้หน้าอกพอดี', 'จุดปรับน้ำหนัก'],
      breathingOut: 'ดึงเข้า (ออกแรง)',
      breathingIn: 'ปล่อยออก',
      cautions: ['พยายามล็อกลำตัวให้หน้าอกติดเบาะด้านหน้าตลอด ไม่โยกตัวหน้า-หลัง', 'เวลาปล่อยแขนออกให้ปล่อยช้าๆ ไม่กระชากหัวไหล่และข้อศอก'],
    },
  },
  {
    exerciseName: 'Shoulder Press',
    category: 'Push', type: 'Compound', difficulty: 2, priority: 'High',
    details: {
      status: '📸 Need photo / 📝 Need setup detail / ⚠️ Use carefully if shoulder feels tight',
      setupChecklist: [
        'ปรับเบาะให้มือจับเริ่มที่ระดับหู/คาง',
        'หลังแนบพนัก ไม่แอ่นหลัง',
        'กดไหล่ลง ไม่ยักไหล่',
        'เริ่มน้ำหนักเบาเพื่อเช็กไหล่',
      ],
      useInWorkout: 'Full Body A/C: ท่าดันหลักของหัวไหล่ — ถ้าไหล่ล้า ให้ลดน้ำหนักหรือข้ามได้',
      mySetting: 'Seat: ? | Weight: ? | Reps: 10 | Note: ?',
      benefits: 'บริหารกล้ามเนื้อหัวไหล่ โดยเฉพาะหัวไหล่ด้านหน้าและด้านข้าง ช่วยเพิ่มความแข็งแรงของหัวไหล่และความมั่นคงของข้อไหล่',
      primaryMuscle: ['หัวไหล่ด้านหน้า (Anterior Deltoid)', 'หัวไหล่ด้านข้าง (Lateral Deltoid)'],
      secondaryMuscle: ['หลังแขน (Triceps)', 'บ่าด้านบน (Upper Trapezius) เล็กน้อย', 'กล้ามเนื้อรอบซี่โครง (Serratus Anterior)'],
      muscleCues: ['ดันขึ้นด้วยหัวไหล่', 'กดไหล่ลง ไม่ยักไหล่', 'เก็บซี่โครง ไม่แอ่นหลัง'],
      feelShould: ['หัวไหล่', 'หลังแขนนิดหน่อย'],
      feelShouldNot: ['หลังล่าง', 'คอ'],
      howTo: [
        'นั่งเต็มเบาะ ศีรษะและหลังแนบพนัก',
        'จับแฮนด์ให้มั่น',
        'ดันขึ้นเหนือศีรษะ',
        'ค่อยๆลดลงอย่างช้าๆ',
      ],
      romDown: 'มือจับอยู่ระดับหูหรือคาง',
      romUp: 'แขนเกือบตรง แต่ไม่ล็อกศอก',
      commonMistakes: ['แอ่นหลัง', 'ยักไหล่', 'ล็อกศอกสุด'],
      adjustmentPoints: ['ปรับเบาะให้มือจับเริ่มต้นอยู่ระดับหูหรือคาง', 'ปรับน้ำหนักตามกำลัง'],
      breathingOut: 'ดันขึ้น',
      breathingIn: 'ลดลง',
      cautions: ['อย่าแอ่นหลัง', 'อย่าเหวี่ยงน้ำหนัก'],
    },
  },
  {
    exerciseName: 'Seated Cable Row',
    category: 'Pull', type: 'Compound', difficulty: 2, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'เลือก attachment ที่เหมาะ (V-handle/bar/rope)',
        'ตั้งเท้าให้แน่นและลำตัวนิ่ง',
        'ตั้งอกก่อนดึง',
        'เลือกน้ำหนักที่ไม่ต้องโยกตัว',
      ],
      useInWorkout: 'Substitute for Low Row เมื่อเครื่อง Low Row ไม่ว่าง — ใช้เป็น pull accessory ได้ในวันที่อยากเพิ่มหลัง',
      mySetting: 'Attachment: ? | Weight: ? | Reps: 10–12 | Note: ?',
      benefits: 'เสริมความหนาหลัง + บีบสะบัก (คล้าย Low Row แต่เป็นสายเคเบิล)',
      primaryMuscle: ['Rhomboids', 'Middle Trapezius'],
      secondaryMuscle: ['Latissimus Dorsi', 'Rear Deltoids', 'Biceps'],
      muscleCues: ['ตั้งอก เชิดหน้าอกเล็กน้อย', 'ดึงด้วย "ศอก" แล้วบีบสะบัก', 'ไม่โยกตัว'],
      feelShould: ['กลางหลัง', 'สะบัก'],
      feelShouldNot: ['หลังล่าง', 'ไหล่งุ้ม'],
      howTo: [
        'นั่งให้มั่นคง วางเท้าให้แน่น และจับ attachment',
        'ตั้งอก เชิดหน้าอกเล็กน้อย แล้วล็อกลำตัว',
        'ดึงด้วย "ศอก" เข้าหาลำตัว แล้วบีบสะบัก',
        'ปล่อยกลับช้าๆ โดยคุมสาย ไม่ปล่อยกระแทก',
      ],
      romDown: 'ปล่อยไปจนไหล่ยืด แต่ยังคุมลำตัว',
      romUp: 'ดึงเข้ามาจนศอกเลยลำตัวเล็กน้อย',
      commonMistakes: ['โยกตัว/ดึงด้วยหลังล่าง', 'ไหล่งุ้มตอนปล่อย'],
      adjustmentPoints: ['เลือก attachment (V-handle/bar/rope)', 'ตั้งเท้า/ระยะนั่งให้ดึงได้เต็มช่วง', 'ปรับน้ำหนัก'],
      breathingOut: 'ดึงเข้า',
      breathingIn: 'ปล่อยออก',
      cautions: ['คุมสาย ไม่ปล่อยกระแทก'],
    },
  },
  {
    exerciseName: 'Leg Curl',
    category: 'Legs', type: 'Isolation', difficulty: 1, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'ปรับลูกกลิ้งให้อยู่เหนือข้อเท้า',
        'จุดหมุนเครื่องตรงกับข้อเข่า',
        'สะโพกไม่ลอย',
        'ลดน้ำหนักถ้ารู้สึกเข่าแทนหลังขา',
      ],
      useInWorkout: 'Full Body B: isolation หลังขา — เล่นหลัง Leg Press',
      mySetting: 'Pad: ? | Weight: ? | Reps: 10–12 | Note: ?',
      benefits: 'บริหารกล้ามเนื้อหลังต้นขา (Hamstrings) ช่วยให้หัวเข่าแข็งแรงและสมดุลกับหน้าขา',
      primaryMuscle: ['หลังต้นขา (Hamstrings)'],
      secondaryMuscle: ['น่อง (Gastrocnemius)'],
      muscleCues: ['คิดว่า "เอาส้นเท้าแตะก้น"', 'บีบหลังขาตอนสุด', 'อย่าใช้สะโพกช่วย'],
      feelShould: ['หลังต้นขา'],
      feelShouldNot: ['เข่า'],
      howTo: ['ปรับเครื่อง', 'งอเข่าดึงลูกกลิ้ง', 'บีบหลังขา', 'ค่อยๆปล่อยกลับ'],
      romDown: 'เหยียดจนเกือบตรง',
      romUp: 'งอจนส้นเท้าเข้าใกล้ก้น',
      commonMistakes: ['ยกสะโพก', 'ปล่อยน้ำหนักกระแทก', 'เร่งจังหวะ'],
      adjustmentPoints: ['ลูกกลิ้งอยู่เหนือข้อเท้า', 'จุดหมุนของเครื่องตรงกับข้อเข่า'],
      breathingOut: 'งอเข่า/ดึงเข้า',
      breathingIn: 'ปล่อยกลับ',
      cautions: ['อย่ากระแทกเข่า', 'อย่าโยกตัว'],
    },
  },
  {
    exerciseName: 'Leg Extension',
    category: 'Legs', type: 'Isolation', difficulty: 1, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'ปรับลูกกลิ้งให้อยู่หน้าแข้งเหนือข้อเท้า',
        'จุดหมุนเครื่องตรงกับข้อเข่า',
        'หลังแนบเบาะ',
        'ไม่ล็อกเข่าสุดตอนเหยียด',
      ],
      useInWorkout: 'Full Body C: isolation หน้าขา / technique day — เล่นหลัง compound หลัก',
      mySetting: 'Pad: ? | Weight: ? | Reps: 12 | Note: ?',
      benefits: 'บริหารกล้ามเนื้อหน้าต้นขา (Quadriceps) ช่วยเพิ่มความแข็งแรงของขาและหัวเข่า',
      primaryMuscle: ['หน้าต้นขา (Quadriceps)'],
      secondaryMuscle: ['ไม่มีอย่างมีนัยสำคัญ (isolation exercise)'],
      muscleCues: ['เตะด้วยหน้าขา', 'บีบหน้าขาตอนสุด', 'หลังแนบเบาะ'],
      feelShould: ['หน้าต้นขา'],
      feelShouldNot: ['เข่า'],
      howTo: ['นั่งเต็มเบาะ', 'เหยียดขา', 'บีบหน้าขา', 'ลดลงช้าๆ'],
      romDown: 'งอเข่าประมาณ 90°',
      romUp: 'เหยียดเกือบสุด แต่ไม่ล็อกเข่า',
      commonMistakes: ['ล็อกเข่า', 'ปล่อยน้ำหนักเร็ว', 'เหวี่ยงขา'],
      adjustmentPoints: ['ลูกกลิ้งอยู่หน้าแข้งเหนือข้อเท้า', 'จุดหมุนเครื่องตรงข้อเข่า'],
      breathingOut: 'เหยียดขา',
      breathingIn: 'ลดลง',
      cautions: ['อย่าล็อกเข่า', 'คุมจังหวะลง'],
    },
  },
  {
    exerciseName: 'Incline Chest Press',
    category: 'Push', type: 'Compound', difficulty: 1, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail / ⚠️ Use carefully if shoulder feels tight',
      setupChecklist: [
        'ปรับเบาะให้มือจับเริ่มที่ระดับอกบน',
        'หลังแนบเบาะ เชิดอกเล็กน้อย',
        'กดไหล่ลงก่อนดัน',
        'เริ่มน้ำหนักเบากว่า Chest Press ปกติ',
      ],
      useInWorkout: 'Optional Push: ใช้เสริมอกบน — Substitute/variation for Chest Press ถ้าอยากเปลี่ยนมุม',
      mySetting: 'Seat: ? | Weight: ? | Reps: 10–12 | Note: ?',
      benefits: 'เน้นอกบน (Upper Chest) และช่วยพัฒนาการดัน',
      primaryMuscle: ['อกบน (Clavicular Head of Pectoralis Major)'],
      secondaryMuscle: ['ไหล่หน้า (Anterior Deltoid)', 'Triceps'],
      muscleCues: ['เชิดอกเล็กน้อย กดไหล่ลง', 'ดัน "เฉียงขึ้น" ตามไลน์ของเครื่อง'],
      feelShould: ['อกบน', 'หน้าไหล่นิดหน่อย'],
      feelShouldNot: ['หัวไหล่เจ็บ'],
      howTo: [
        'ปรับเบาะให้อยู่ตำแหน่งที่มือจับเริ่มต้นแถวอกบน',
        'นั่งหลังแนบเบาะ เชิดอกเล็กน้อย และกดไหล่ลง',
        'ดันแฮนเดิลเฉียงขึ้นตามไลน์ของเครื่อง',
        'ปล่อยกลับช้าๆ โดยไม่ให้ไหล่หลุดตำแหน่ง',
      ],
      romDown: 'อกตึงแต่ไม่ให้ไหล่หลุด/เจ็บ',
      romUp: 'แขนเกือบตรง ไม่ล็อกศอก',
      commonMistakes: ['ยักไหล่', 'ศอกกางสูงเกินไป'],
      adjustmentPoints: ['ปรับเบาะให้มือจับเริ่มต้นอยู่ระดับอกบน', 'ปรับน้ำหนัก'],
      breathingOut: 'ดันออก',
      breathingIn: 'ปล่อยกลับ',
      cautions: ['ถ้าเจ็บไหล่ ลด ROM/ลดน้ำหนัก และคุมสะบัก'],
    },
  },
  {
    exerciseName: 'Arm Extension',
    category: 'Push', type: 'Isolation', difficulty: 1, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'ปรับที่นั่ง/จุดวางศอกให้พอดี',
        'ศอกนิ่ง ไม่ลอย',
        'ไม่ล็อกข้อศอกสุด',
        'คุมน้ำหนักทั้งขึ้นและลง',
      ],
      useInWorkout: 'Optional Push accessory หลัง Chest/Shoulder Press — ใช้เสริมหลังแขนเมื่อยังมีแรง',
      mySetting: 'Seat: ? | Weight: ? | Reps: 10–15 | Note: ?',
      benefits: 'เน้นหลังแขน (Triceps) เพิ่มแรงเหยียดศอก',
      primaryMuscle: ['Triceps'],
      secondaryMuscle: ['ไม่มีเด่น (ขึ้นกับทรงเครื่อง)'],
      muscleCues: ['ศอก "นิ่ง" ไม่แกว่งไปมา', 'เหยียดด้วยหลังแขน ไม่ใช่โยกไหล่'],
      feelShould: ['หลังแขน'],
      feelShouldNot: ['ศอกเจ็บ', 'ไหล่ทำงานแทน'],
      howTo: [
        'ปรับที่นั่ง/จุดวางศอกให้พอดี',
        'วางศอกให้นิ่ง แล้วจับแฮนเดิล',
        'เหยียดแขนด้วยหลังแขนจนเกือบสุด',
        'ค่อยๆงอกลับโดยคุมน้ำหนัก',
      ],
      romDown: 'เหยียดจนเกือบสุด แต่ไม่ล็อกข้อศอก',
      romUp: 'งอกลับจนตึง',
      commonMistakes: ['ใช้ตัวโยกช่วย', 'ปล่อยน้ำหนักกระแทก'],
      adjustmentPoints: ['ปรับที่นั่ง/จุดวางศอกให้พอดี', 'ปรับน้ำหนัก'],
      breathingOut: 'เหยียดแขน',
      breathingIn: 'งอกลับ',
      cautions: ['ระวังเจ็บศอก: คุมจังหวะ, ไม่ล็อกสุด'],
    },
  },
  {
    exerciseName: 'Abdominal Crunch',
    category: 'Core', type: 'Isolation', difficulty: 1, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'ปรับเบาะ/ระยะให้หลังส่วนล่างแนบพอดี',
        'เริ่มน้ำหนักเบาเพื่อจับความรู้สึกหน้าท้อง',
        'ไม่ดึงด้วยคอหรือไหล่',
        'คุมจังหวะกลับ',
      ],
      useInWorkout: 'Core finisher หลังเวทหลัก — ใช้แทน plank ในวันที่อยากเล่นเครื่อง',
      mySetting: 'Seat: ? | Weight: ? | Reps: 12–15 | Note: ?',
      benefits: 'เน้นซิกแพค (Rectus Abdominis) ให้รู้สึกชัดและคุมได้',
      primaryMuscle: ['Rectus Abdominis'],
      secondaryMuscle: ['Obliques (เล็กน้อย)'],
      muscleCues: ['"ม้วนซี่โครงเข้าหาเชิงกราน" (ribcage to pelvis)', 'หายใจออกตอน crunch'],
      feelShould: ['หน้าท้อง'],
      feelShouldNot: ['คอ', 'หลังล่าง'],
      howTo: [
        'ปรับเบาะ/ระยะให้หลังส่วนล่างแนบพอดี',
        'จับแฮนเดิลหรือวางแขนตามเครื่อง',
        'ม้วนซี่โครงเข้าหาเชิงกรานโดยใช้หน้าท้อง',
        'คลายกลับช้าๆ ไม่ปล่อยเด้ง',
      ],
      romDown: 'งอ/ม้วนจนท้องหด',
      romUp: 'คลายกลับช้าๆ ไม่ปล่อยเด้ง',
      commonMistakes: ['ดึงด้วยแขน/ไหล่', 'แอ่นหลังตอนกลับ'],
      adjustmentPoints: ['ปรับเบาะ/ระยะให้หลังส่วนล่างแนบพอดี', 'ปรับน้ำหนัก'],
      breathingOut: 'Crunch',
      breathingIn: 'คลายกลับ',
      cautions: ['หลีกเลี่ยงการกระตุกคอ/ไหล่'],
    },
  },
  {
    exerciseName: 'Face Pull',
    category: 'Pull', type: 'Isolation', difficulty: 3, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'ตั้งรอกระดับหน้า',
        'ใช้ Rope Attachment',
        'ถอยหลังให้สายตึงก่อนเริ่ม',
        'เลือกน้ำหนักเบา คุมฟอร์มก่อน',
      ],
      useInWorkout: 'Full Body A: accessory หลัง/ไหล่หลัง — Recovery Day: ท่าเบาๆ ช่วย posture',
      mySetting: 'Pulley height: ? | Weight: ? | Reps: 12–15 | Note: ?',
      benefits: 'บริหารหัวไหล่ด้านหลัง และกล้ามเนื้อสะบัก ช่วยแก้ไหล่งุ้มและเพิ่มความมั่นคงของหัวไหล่',
      primaryMuscle: ['หัวไหล่ด้านหลัง (Rear Deltoids)'],
      secondaryMuscle: ['สะบัก (Rhomboids)', 'กลางหลัง (Middle Trapezius)', 'หลังส่วนล่างของสะบัก (Lower Trapezius)', 'กล้ามเนื้อพยุงข้อไหล่ (Rotator Cuff)'],
      muscleCues: ['ดึงเชือกเข้าหาใบหน้า', 'กางศอก', 'บีบสะบัก'],
      feelShould: ['หลังไหล่', 'สะบัก'],
      feelShouldNot: ['คอ'],
      howTo: ['จับปลายเชือก', 'ถอยหลังให้สายตึง', 'ดึงเข้าหาใบหน้า', 'แยกปลายเชือกออกจากกัน'],
      romDown: 'แขนเหยียดจนยังตึงสาย',
      romUp: 'ดึงจนมืออยู่ข้างหู',
      commonMistakes: ['ดึงลงอก', 'ยักไหล่', 'ใช้หลังแอ่น'],
      adjustmentPoints: ['ตั้งสายไว้ระดับหน้า', 'ใช้ Rope Attachment'],
      breathingOut: 'ดึงเข้า',
      breathingIn: 'ปล่อยออก',
      cautions: ['อย่าเหวี่ยงตัว', 'อย่าดึงด้วยแขนอย่างเดียว'],
    },
  },
  {
    exerciseName: 'Adjustable Pulley',
    category: 'Full Body', type: 'Compound/Isolation', difficulty: 2, priority: 'Medium',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'เลือกระดับรอกก่อน (สูง/กลาง/ต่ำ)',
        'เลือก attachment ให้ตรงท่า',
        'ยืนให้สายตึงเล็กน้อยก่อนเริ่ม',
        'ล็อกลำตัว ไม่แกว่ง',
      ],
      useInWorkout: 'Substitute/accessory ได้หลายท่า เช่น row, triceps, face pull, cable fly — ใช้เติม volume เมื่อเครื่องหลักไม่ว่าง',
      mySetting: 'Pulley height: ? | Attachment: ? | Weight: ? | Reps: ? | Note: ?',
      benefits: 'เล่นได้สารพัดท่า (Push/Pull/Legs/Abs) ปรับมุมแรงต้านได้',
      primaryMuscle: ['ตามท่าที่เล่น (เช่น Chest / Back / Shoulders / Arms / Core)'],
      secondaryMuscle: ['Core (ช่วยคุมลำตัว)'],
      muscleCues: ['ล็อกลำตัวนิ่ง คุมสายไม่ให้สะบัด', 'ดึง/ดัน "ด้วยกล้ามเนื้อเป้าหมาย" ไม่ใช่แกว่งตัว'],
      feelShould: ['กล้ามเนื้อเป้าหมายของท่านั้น'],
      feelShouldNot: ['ข้อต่อเจ็บ', 'หลังล่างทำงานแทน'],
      howTo: ['ตั้งรอก + ใส่ attachment', 'ก้าวเท้าหาตำแหน่งที่สายตึงเล็กน้อย', 'หายใจออกตอนออกแรง / หายใจเข้าตอนผ่อน'],
      romDown: 'ไปสุดช่วงที่ยัง "คุม" ได้ และยังรู้สึกตึงที่กล้ามเนื้อเป้าหมาย',
      commonMistakes: ['แกว่งตัว/ใช้แรงเหวี่ยง', 'ปล่อยสายกระแทกกลับ'],
      adjustmentPoints: ['ปรับระดับรอก (สูง/กลาง/ต่ำ)', 'เลือก attachment (handle/rope/bar/ankle strap)', 'ปรับน้ำหนัก'],
      breathingOut: 'ออกแรง',
      breathingIn: 'ผ่อนแรง',
      cautions: ['ระวังไหล่หลุดตำแหน่ง (ไม่ยักไหล่ ไม่บิดหลัง)'],
    },
  },
  {
    exerciseName: 'Pectoral',
    category: 'Push', type: 'Isolation', difficulty: 1, priority: 'Low',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'ปรับเบาะให้มือจับ/แผ่นรองอยู่ระดับอก',
        'ตั้งระยะเริ่มต้นไม่ให้เปิดอกลึกเกิน',
        'หลังแนบเบาะ',
        'คุมจังหวะเปิดกลับ',
      ],
      useInWorkout: 'Full Body B: แทน Chest Press เพื่อลดการกดหนักหน้าอกซ้ำ — Optional chest isolation',
      mySetting: 'Seat: ? | Start range: ? | Weight: ? | Reps: 12–15 | Note: ?',
      benefits: 'บริหารกล้ามเนื้อหน้าอก โดยเน้นการบีบอก ช่วยเพิ่มการรับรู้การทำงานของกล้ามเนื้อหน้าอก (Mind-Muscle Connection)',
      primaryMuscle: ['หน้าอก (Pectoralis Major)'],
      secondaryMuscle: ['หัวไหล่ด้านหน้า (Anterior Deltoid)'],
      muscleCues: ['กอดต้นไม้ใหญ่', 'บีบอกเข้าหากัน', 'อย่ายักไหล่'],
      feelShould: ['หน้าอก'],
      feelShouldNot: ['หัวไหล่'],
      howTo: ['นั่งหลังแนบเบาะ', 'จับที่จับหรือวางแขนบนแผ่นรอง', 'บีบแขนเข้าหากัน', 'ค่อยๆเปิดกลับ'],
      romDown: 'เปิดจนอกตึง',
      romUp: 'ปิดจนมือเกือบชนกัน',
      commonMistakes: ['เปิดกว้างเกิน', 'เหวี่ยงน้ำหนัก', 'ใช้ไหล่แทนอก'],
      adjustmentPoints: ['ปรับเบาะให้มือจับอยู่ระดับอก', 'ปรับระยะเริ่มต้นให้เปิดอกได้พอดี'],
      breathingOut: 'บีบเข้า',
      breathingIn: 'เปิดกลับ',
      cautions: ['อย่าเปิดจนไหล่ตึงเกิน', 'คุมจังหวะทั้งไปและกลับ'],
    },
  },
  {
    exerciseName: 'Lower Back',
    category: 'Legs/Core', type: 'Isolation', difficulty: 1, priority: 'Low',
    details: {
      status: '📸 Need photo / 📝 Need setup detail / ⚠️ Use carefully if lower back feels sensitive',
      setupChecklist: [
        'ปรับเบาะ/จุดพิงให้ตรงสะโพก',
        'คอเป็นกลาง ไม่เงย',
        'ขึ้นจนลำตัวตรงพอ ไม่แอ่นสุด',
        'เริ่มน้ำหนักเบาหรือ bodyweight ก่อน',
      ],
      useInWorkout: 'Optional posterior-chain accessory — ใช้เฉพาะวันที่หลังล่างไม่ล้า',
      mySetting: 'Pad: ? | Weight: ? | Reps: 12–15 | Note: ?',
      benefits: 'เสริมความแข็งแรงหลังล่าง/สะโพก ช่วยพยุงท่า compound',
      primaryMuscle: ['Erector Spinae (หลังล่าง)'],
      secondaryMuscle: ['Glutes', 'Hamstrings (เล็กน้อย)'],
      muscleCues: ['"งอ/เหยียดจากสะโพก" ไม่ใช่แอ่นหลัง', 'เก็บซี่โครง ไม่เงยคอ'],
      feelShould: ['หลังล่างแบบทำงาน', 'ก้น/หลังขาเล็กน้อย'],
      feelShouldNot: ['ปวดแปลบที่หลังล่าง'],
      howTo: [
        'ปรับตำแหน่งเบาะ/จุดพิงให้พอดีสะโพก',
        'เก็บซี่โครง คอเป็นกลาง',
        'ก้มลงโดยคุมจากสะโพก',
        'เหยียดกลับจนลำตัวตรง ไม่แอ่นเกิน',
      ],
      romDown: 'ก้มลงจนตึงที่ก้น/หลังขาเล็กน้อย',
      romUp: 'ขึ้นจนลำตัวตรง ไม่แอ่นเกิน',
      commonMistakes: ['แอ่นหลังสุด', 'กระตุก/เหวี่ยง'],
      adjustmentPoints: ['ปรับตำแหน่งเบาะ/จุดพิงให้พอดีสะโพก', 'ปรับน้ำหนัก (ถ้ามี)'],
      breathingOut: 'เหยียดขึ้น',
      breathingIn: 'ก้มลง',
      cautions: ['ถ้าเจ็บหลังล่าง: ลด ROM, ลดน้ำหนัก, โฟกัส hip hinge'],
    },
  },
  {
    exerciseName: 'Rotary Torso',
    category: 'Core', type: 'Isolation', difficulty: 2, priority: 'Low',
    details: {
      status: '📸 Need photo / 📝 Need setup detail / ⚠️ Use carefully if lower back feels sensitive',
      setupChecklist: [
        'ปรับมุมเริ่มต้นสั้นๆก่อน',
        'ล็อกสะโพก ไม่หมุนตาม',
        'บิดช้าๆ ไม่กระชาก',
        'เริ่มน้ำหนักเบามาก',
      ],
      useInWorkout: 'Optional core accessory — ไม่จำเป็นสำหรับวันหลัก ถ้าเวลาน้อยให้ข้ามได้',
      mySetting: 'Start angle: ? | Weight: ? | Reps: ? | Note: ?',
      benefits: 'ฝึกกล้ามท้องด้านข้าง (Obliques) และการต้านการบิดลำตัว',
      primaryMuscle: ['Obliques'],
      secondaryMuscle: ['กล้ามเนื้อแกนกลางอื่นๆ (Core stabilizers)'],
      muscleCues: ['บิดจาก "ลำตัวส่วนบน" โดยไม่ให้สะโพกหมุนตามมาก', 'คุมช้าๆทั้งไปและกลับ'],
      feelShould: ['ท้องด้านข้าง'],
      feelShouldNot: ['หลังล่างเจ็บ', 'สะโพกหมุนแทน'],
      howTo: [
        'ปรับระยะ/มุมเริ่มต้นให้เหมาะ',
        'ล็อกสะโพกและลำตัวช่วงล่าง',
        'บิดจากลำตัวส่วนบนอย่างช้าๆ',
        'คุมกลับ ไม่ปล่อยน้ำหนักกระแทก',
      ],
      romDown: 'บิดได้เท่าที่ไม่เจ็บหลัง/สะโพก',
      commonMistakes: ['บิดแรง/เร็วเกิน', 'ใช้สะโพกหมุนแทนลำตัว'],
      adjustmentPoints: ['ปรับระยะ/มุมเริ่มต้น (ถ้ามี)', 'ปรับน้ำหนัก'],
      breathingOut: 'บิดออกแรง',
      breathingIn: 'กลับจุดเริ่ม',
      cautions: ['ถ้ามีประวัติปวดหลังส่วนล่าง ให้เริ่มเบามากและ ROM สั้น'],
    },
  },
  {
    exerciseName: 'Abductor',
    category: 'Legs', type: 'Isolation', difficulty: 1, priority: 'Low',
    details: {
      status: '📸 Need photo / 📝 Need setup detail',
      setupChecklist: [
        'หลังแนบพนัก',
        'ตั้งช่วงเริ่มต้นให้สะโพกไม่ตึงเกิน',
        'ถ่างจากก้นด้านข้าง ไม่โยกตัว',
        'คุมจังหวะกลับ',
      ],
      useInWorkout: 'Optional glute/hip accessory — ใช้เป็น warm-up หรือ finisher เบาๆได้',
      mySetting: 'Start range: ? | Weight: ? | Reps: 12–15 | Note: ?',
      benefits: 'เสริมก้นด้านข้าง ช่วยเสถียรภาพสะโพก/เข่า',
      primaryMuscle: ['Gluteus Medius/Minimus'],
      secondaryMuscle: ['Tensor Fasciae Latae (TFL) เล็กน้อย'],
      muscleCues: ['หลังแนบพนัก เก็บลำตัวนิ่ง', '"ถ่างจากก้น" ไม่ใช่โยกตัว'],
      feelShould: ['ก้นด้านข้าง'],
      feelShouldNot: ['ขาหนีบเจ็บ', 'หลังล่าง'],
      howTo: [
        'นั่งหลังแนบพนักและวางขากับแผ่นรอง',
        'เก็บลำตัวนิ่ง',
        'ถ่างขาออกโดยโฟกัสก้นด้านข้าง',
        'ค่อยๆกลับช้าๆ',
      ],
      romDown: 'ถ่างจนตึง แล้วค่อยๆกลับช้าๆ',
      commonMistakes: ['เด้ง/ปล่อยกระแทก', 'โยกตัวช่วย'],
      adjustmentPoints: ['ปรับองศาเริ่มต้น (ถ้ามี)', 'ปรับน้ำหนัก'],
      breathingOut: 'ถ่างออก',
      breathingIn: 'กลับเข้า',
      cautions: ['ไม่ต้องถ่างสุดถ้าเริ่มเจ็บสะโพก/ขาหนีบ'],
    },
  },
]
